import { DEPARTMENTS, DESIGNATIONS, STATUS } from './constants';

// ── Employees ─────────────────────────────────────────────
export const mockEmployees = [
  {
    id: '1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@workforce.io',
    phone: '9876543210',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    status: STATUS.ACTIVE,
    joinDate: '2023-03-15',
    salary: 1200000,
    avatar: null,
  },
  {
    id: '2',
    name: 'Priya Patel',
    email: 'priya.patel@workforce.io',
    phone: '9876543211',
    department: 'Human Resources',
    designation: 'HR Manager',
    status: STATUS.ACTIVE,
    joinDate: '2022-07-01',
    salary: 950000,
    avatar: null,
  },
  {
    id: '3',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@workforce.io',
    phone: '9876543212',
    department: 'Marketing',
    designation: 'Marketing Analyst',
    status: STATUS.ON_LEAVE,
    joinDate: '2024-01-10',
    salary: 750000,
    avatar: null,
  },
  {
    id: '4',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@workforce.io',
    phone: '9876543213',
    department: 'Design',
    designation: 'UI/UX Designer',
    status: STATUS.ACTIVE,
    joinDate: '2023-09-20',
    salary: 850000,
    avatar: null,
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram.singh@workforce.io',
    phone: '9876543214',
    department: 'Engineering',
    designation: 'Tech Lead',
    status: STATUS.ACTIVE,
    joinDate: '2021-11-05',
    salary: 1800000,
    avatar: null,
  },
  {
    id: '6',
    name: 'Ananya Mishra',
    email: 'ananya.mishra@workforce.io',
    phone: '9876543215',
    department: 'Finance',
    designation: 'Finance Analyst',
    status: STATUS.ACTIVE,
    joinDate: '2024-02-14',
    salary: 700000,
    avatar: null,
  },
  {
    id: '7',
    name: 'Karan Mehta',
    email: 'karan.mehta@workforce.io',
    phone: '9876543216',
    department: 'Sales',
    designation: 'Sales Executive',
    status: STATUS.INACTIVE,
    joinDate: '2022-05-30',
    salary: 650000,
    avatar: null,
  },
  {
    id: '8',
    name: 'Divya Nair',
    email: 'divya.nair@workforce.io',
    phone: '9876543217',
    department: 'Product',
    designation: 'Product Manager',
    status: STATUS.ACTIVE,
    joinDate: '2023-06-18',
    salary: 1400000,
    avatar: null,
  },
  {
    id: '9',
    name: 'Arjun Kumar',
    email: 'arjun.kumar@workforce.io',
    phone: '9876543218',
    department: 'Engineering',
    designation: 'DevOps Engineer',
    status: STATUS.ACTIVE,
    joinDate: '2024-04-01',
    salary: 1100000,
    avatar: null,
  },
  {
    id: '10',
    name: 'Meera Joshi',
    email: 'meera.joshi@workforce.io',
    phone: '9876543219',
    department: 'Customer Support',
    designation: 'QA Engineer',
    status: STATUS.ACTIVE,
    joinDate: '2023-12-01',
    salary: 800000,
    avatar: null,
  },
  {
    id: '11',
    name: 'Rahul Verma',
    email: 'rahul.verma@workforce.io',
    phone: '9876543220',
    department: 'Engineering',
    designation: 'Software Engineer',
    status: STATUS.ACTIVE,
    joinDate: '2024-06-15',
    salary: 900000,
    avatar: null,
  },
  {
    id: '12',
    name: 'Pooja Iyer',
    email: 'pooja.iyer@workforce.io',
    phone: '9876543221',
    department: 'Legal',
    designation: 'Business Analyst',
    status: STATUS.ON_LEAVE,
    joinDate: '2022-10-10',
    salary: 780000,
    avatar: null,
  },
  {
    id: '13',
    name: 'Nishant Rao',
    email: 'nishant.rao@workforce.io',
    phone: '9876543222',
    department: 'Operations',
    designation: 'Engineering Manager',
    status: STATUS.ACTIVE,
    joinDate: '2021-08-22',
    salary: 2000000,
    avatar: null,
  },
  {
    id: '14',
    name: 'Tanya Kapoor',
    email: 'tanya.kapoor@workforce.io',
    phone: '9876543223',
    department: 'Marketing',
    designation: 'Data Analyst',
    status: STATUS.ACTIVE,
    joinDate: '2024-03-05',
    salary: 720000,
    avatar: null,
  },
  {
    id: '15',
    name: 'Siddharth Bose',
    email: 'siddharth.bose@workforce.io',
    phone: '9876543224',
    department: 'Engineering',
    designation: 'Senior Software Engineer',
    status: STATUS.ACTIVE,
    joinDate: '2023-01-25',
    salary: 1300000,
    avatar: null,
  },
];

// ── Dashboard stats ───────────────────────────────────────
export const mockDashboardStats = [
  {
    id: 'total-employees',
    label: 'Total Employees',
    value: 156,
    change: +4.2,
    icon: 'users',
    color: 'primary',
  },
  {
    id: 'present-today',
    label: 'Present Today',
    value: 142,
    change: -1.8,
    icon: 'check-circle',
    color: 'success',
  },
  {
    id: 'pending-leaves',
    label: 'Pending Leaves',
    value: 8,
    change: +12.5,
    icon: 'calendar',
    color: 'warning',
  },
  {
    id: 'open-tickets',
    label: 'Open Tickets',
    value: 23,
    change: -6.3,
    icon: 'headphones',
    color: 'danger',
  },
];

// ── Recent activities ─────────────────────────────────────
export const mockRecentActivities = [
  {
    id: '1',
    action: 'New employee onboarded',
    description: 'Rahul Verma joined the Engineering team',
    time: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    type: 'success',
  },
  {
    id: '2',
    action: 'Leave approved',
    description: "Pooja Iyer's casual leave has been approved",
    time: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    type: 'info',
  },
  {
    id: '3',
    action: 'Payroll processed',
    description: 'June 2026 payroll has been processed for 156 employees',
    time: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    type: 'success',
  },
  {
    id: '4',
    action: 'Helpdesk ticket raised',
    description: 'Karan Mehta raised a ticket for laptop replacement',
    time: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    type: 'warning',
  },
  {
    id: '5',
    action: 'Performance review due',
    description: 'Q2 performance reviews are due in 3 days',
    time: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    type: 'danger',
  },
  {
    id: '6',
    action: 'New candidate shortlisted',
    description: 'Meghna Das shortlisted for Senior Designer role',
    time: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    type: 'info',
  },
];

// ── Attendance trend (7 days) ─────────────────────────────
export const mockAttendanceTrend = [
  { day: 'Mon', present: 148, absent: 8 },
  { day: 'Tue', present: 151, absent: 5 },
  { day: 'Wed', present: 142, absent: 14 },
  { day: 'Thu', present: 145, absent: 11 },
  { day: 'Fri', present: 138, absent: 18 },
  { day: 'Sat', present: 52, absent: 0 },
  { day: 'Sun', present: 0, absent: 0 },
];

// ── Department distribution ───────────────────────────────
export const mockDepartmentDistribution = [
  { department: 'Engineering', count: 48, color: '#4F46E5' },
  { department: 'Human Resources', count: 12, color: '#7C3AED' },
  { department: 'Marketing', count: 18, color: '#EC4899' },
  { department: 'Sales', count: 22, color: '#F59E0B' },
  { department: 'Finance', count: 14, color: '#10B981' },
  { department: 'Operations', count: 16, color: '#3B82F6' },
  { department: 'Product', count: 10, color: '#6366F1' },
  { department: 'Design', count: 8, color: '#F97316' },
  { department: 'Customer Support', count: 6, color: '#14B8A6' },
  { department: 'Legal', count: 2, color: '#8B5CF6' },
];

// ── Quick actions ─────────────────────────────────────────
export const mockQuickActions = [
  { label: 'Add Employee', path: '/employees/add', icon: 'user-plus', color: 'primary' },
  { label: 'Mark Attendance', path: '/attendance', icon: 'check-circle', color: 'success' },
  { label: 'Apply Leave', path: '/leave', icon: 'calendar', color: 'warning' },
  { label: 'Create Ticket', path: '/helpdesk', icon: 'headphones', color: 'danger' },
  { label: 'Run Payroll', path: '/payroll', icon: 'dollar-sign', color: 'secondary' },
  { label: 'View Reports', path: '/analytics', icon: 'bar-chart-2', color: 'info' },
];
